### PR TITLE
Adding primary care flags to mcaid_claim_header

### PR DESCRIPTION
**Pull request by alastairmatheson**
Philip (or @seh315), can you please take a look at the commits and make sure I have implemented the logic correctly? I've loaded a new stage.mcaid_claim_header table.

### CODE REVIEW

**Comment by seh315** [comment]
> Philip (or @seh315), can you please take a look at the commits and make sure I have implemented the logic correctly? I've loaded a new stage.mcaid_claim_header table.

Looks good. One thing my code did not contain is exclusions for visits/procedures that took place in an inpatient, swing bed, and free-standing ambulatory care center . Do you plan do exclude this later?

**Comment by alastairmatheson** [comment]
> > Philip (or @seh315), can you please take a look at the commits and make sure I have implemented the logic correctly? I've loaded a new stage.mcaid_claim_header table.
> 
> Looks good. One thing my code did not contain is exclusions for visits/procedures that took place in an inpatient, swing bed, and free-standing ambulatory care center . Do you plan do exclude this later?

It's already in the code here:
https://github.com/PHSKC-APDE/claims_data/pull/79/commits/8908f2ceb08ac5595ad114eefa4625a2e3cbe80d#diff-f3dca4f705a27097504d69cd84f5c9c4R453
Though this only covers inpatient and ACCs since we can't identify swing beds.

**Comment by seh315** [comment]
> > > Philip (or @seh315), can you please take a look at the commits and make sure I have implemented the logic correctly? I've loaded a new stage.mcaid_claim_header table.
> > 
> > 
> > Looks good. One thing my code did not contain is exclusions for visits/procedures that took place in an inpatient, swing bed, and free-standing ambulatory care center . Do you plan do exclude this later?
> 
> It's already in the code here:
> [8908f2c#diff-f3dca4f705a27097504d69cd84f5c9c4R453](https://github.com/PHSKC-APDE/claims_data/commit/8908f2ceb08ac5595ad114eefa4625a2e3cbe80d#diff-f3dca4f705a27097504d69cd84f5c9c4R453)
> Though this only covers inpatient and ACCs since we can't identify swing beds.

Great!

**Comment by pwsylling** [comment]
The logic looks great. Sorry to be a nitpick but I noticed two CPTs in the script are 99495
99496. The ref.pc_visit_oregon table doesn't appear to have these but has 99445
99446. Are these a mismatch?
-Philip

**Comment by alastairmatheson** [comment]
> The logic looks great. Sorry to be a nitpick but I noticed two CPTs in the script are 99495
> 99496. The ref.pc_visit_oregon table doesn't appear to have these but has 99445
> 99446. Are these a mismatch?
> -Philip

Nitpicking is good. I'll defer to @seh315 on this question since I just copied the SQL but it does look like they should be changed. I actually didn't notice this ref table existed. Should we change the code to refer to that instead?

**Comment by seh315** [comment]
> The logic looks great. Sorry to be a nitpick but I noticed two CPTs in the script are 99495
> 99496. The ref.pc_visit_oregon table doesn't appear to have these but has 99445
> 99446. Are these a mismatch?
> -Philip

Hi All,
I double checked the reference article which can be found here:  https://documentcloud.adobe.com/link/track?uri=urn%3Aaaid%3Ascds%3AUS%3A949be41e-7726-4525-9aa0-e3592cbab4b7

Looks like 99495-99496 Transitional Care Management Services IS part of the definition.  

99445 &  99446  ARE NOT listed in the OR definition

**Comment by elikern-kc** [comment]
Hi all,

The APCD code for apcd_claim_header table refers to the ref.pc_visit_oregon table, and thus I would recommend using that instead of hardcoding the codes!

Eli

Eli Kern MPH RN | Epidemiologist
Assessment, Policy Development, and Evaluation
Public Health - Seattle and King County<https://owa.kingcounty.gov/owa/redir.aspx?C=TNuruUR_x0mMeOqn6rueKCfnLzCcxdAICR3iDfSS8atu12V25XSLIp_1k_j_A9NKOb-a_2dkPVw.&URL=http%3a%2f%2fwww.kingcounty.gov%2fhealthservices%2fhealth.aspx>
phone: 206.263.8727 | email: eli.kern@kingcounty.gov<https://owa.kingcounty.gov/owa/redir.aspx?C=TNuruUR_x0mMeOqn6rueKCfnLzCcxdAICR3iDfSS8atu12V25XSLIp_1k_j_A9NKOb-a_2dkPVw.&URL=mailto%3aeli.kern%40kingcounty.gov>

**Comment by seh315** [comment]
Hi Eli,
Seems like there is a discrepancy between the OR reference article and the SQL reference table.

**Comment by elikern-kc** [comment]
Sure enough, that’s my fault! 99445 and 99446 are my typo, I will fix and re-run the ref table momentarily.

Apologies!

Eli

Eli Kern MPH RN | Epidemiologist
Assessment, Policy Development, and Evaluation
Public Health - Seattle and King County<https://owa.kingcounty.gov/owa/redir.aspx?C=TNuruUR_x0mMeOqn6rueKCfnLzCcxdAICR3iDfSS8atu12V25XSLIp_1k_j_A9NKOb-a_2dkPVw.&URL=http%3a%2f%2fwww.kingcounty.gov%2fhealthservices%2fhealth.aspx>
phone: 206.263.8727 | email: eli.kern@kingcounty.gov<https://owa.kingcounty.gov/owa/redir.aspx?C=TNuruUR_x0mMeOqn6rueKCfnLzCcxdAICR3iDfSS8atu12V25XSLIp_1k_j_A9NKOb-a_2dkPVw.&URL=mailto%3aeli.kern%40kingcounty.gov>

**Comment by elikern-kc** [comment]
Ok, the ref.pc_visit_oregon table has been fixed. Which means I have to re-run the apcd_claim_header table at some point, but I may just wait until we have new APCD data at which point the problem will correct itself 😊

Eli

Eli Kern MPH RN | Epidemiologist
Assessment, Policy Development, and Evaluation
Public Health - Seattle and King County<https://owa.kingcounty.gov/owa/redir.aspx?C=TNuruUR_x0mMeOqn6rueKCfnLzCcxdAICR3iDfSS8atu12V25XSLIp_1k_j_A9NKOb-a_2dkPVw.&URL=http%3a%2f%2fwww.kingcounty.gov%2fhealthservices%2fhealth.aspx>
phone: 206.263.8727 | email: eli.kern@kingcounty.gov<https://owa.kingcounty.gov/owa/redir.aspx?C=TNuruUR_x0mMeOqn6rueKCfnLzCcxdAICR3iDfSS8atu12V25XSLIp_1k_j_A9NKOb-a_2dkPVw.&URL=mailto%3aeli.kern%40kingcounty.gov>

From: Kern, Eli
Sent: Wednesday, January 29, 2020 11:00 AM
To: PHSKC-APDE/claims_data <reply@reply.github.com>; PHSKC-APDE/claims_data <claims_data@noreply.github.com>
Cc: Comment <comment@noreply.github.com>
Subject: RE: [PHSKC-APDE/claims_data] Adding primary care flags to mcaid_claim_header (#79)

Sure enough, that’s my fault! 99445 and 99446 are my typo, I will fix and re-run the ref table momentarily.

Apologies!

Eli

Eli Kern MPH RN | Epidemiologist
Assessment, Policy Development, and Evaluation
Public Health - Seattle and King County<https://owa.kingcounty.gov/owa/redir.aspx?C=TNuruUR_x0mMeOqn6rueKCfnLzCcxdAICR3iDfSS8atu12V25XSLIp_1k_j_A9NKOb-a_2dkPVw.&URL=http%3a%2f%2fwww.kingcounty.gov%2fhealthservices%2fhealth.aspx>
phone: 206.263.8727 | email: eli.kern@kingcounty.gov<https://owa.kingcounty.gov/owa/redir.aspx?C=TNuruUR_x0mMeOqn6rueKCfnLzCcxdAICR3iDfSS8atu12V25XSLIp_1k_j_A9NKOb-a_2dkPVw.&URL=mailto%3aeli.kern%40kingcounty.gov>

**Comment by alastairmatheson** [comment]
Primary care flags need a bit more QA but merging in for now

**Pull request merged**
